version: '3.6'
services:
  postgres:
    restart: always
    image: unnotech/postgres-replication:10.4
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - ./env/.postgres
      - ./env/.env
  django:
    restart: always
    image: deanunnotech/django:master
    build: ./django
    volumes:
      - ./django:/usr/src/app/
    env_file:
      - ./env/.postgres
      - ./env/.env
    build:
      context: ./django
      args:
        - CIRCLE_BRANCH=master
  nginx:
    restart: always
    image: nginx:1.13.9
    volumes:
      - ./django/static:/usr/src/app/django/static
      - ./django/media:/usr/src/app/django/media
      - ./angularjs:/usr/src/app/angularjs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    build: ./nginx
    env_file:
      - ./env/.env
    ports:
      - published: 80
        target: 80
        mode: host
      - published: 8000
        target: 8000
        mode: host
  # angularjs:
  #   restart: always
  #   image: deanunnotech/angularjs:latest
  #   build: ./angularjs
  #   env_file:
  #     - ./env/.env
  #   ports:
  #     - 4200:4200
  #     - 49153:49153
  #   volumes:
  #     - ./angularjs:/usr/src/app/
  vuejs:
    restart: always
    image: deanunnotech/vuejs:latest
    build: ./vuejs
    env_file:
      - ./env/.env
    ports:
      - 3000:3000
    volumes:
      - ./vuejs:/usr/src/app/
    entrypoint: /usr/src/app/dev-entrypoint.sh
  # selenium-python:
  #   restart: always
  #   image: python:3.6.4
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./selenium:/usr/src/app/
  # selenium-firefox:
  #   restart: always
  #   image: selenium/standalone-firefox:3.141.59
  #   volumes:
  #     - /dev/shm:/dev/shm
  # selenium-chrome:
  #   restart: always
  #   image: selenium/standalone-chrome:3.141.59
  #   volumes:
  #     - /dev/shm:/dev/shm

