version: '3.6'
services:
  postgres:
    restart: always
    image: unnotech/postgres-replication:10.4
    # image: infrastructureplayground/postgres:latest
    # build: ./postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      # - ./postgres/docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - ./env/.postgres
      - ./env/.env
  django:
    restart: always
    image: infrastructureplayground/django:master
    build: ./django
    volumes:
      - ./django:/usr/src/app/
    env_file:
      - ./env/.postgres
      - ./env/.env
    build:
      context: ./django
      args:
        - CIRCLE_BRANCH=master
  nginx:
    restart: always
    image: nginx:1.13.9
    volumes:
      - ./django/static:/usr/src/app/django/static
      - ./django/media:/usr/src/app/django/media
      - ./angularjs:/usr/src/app/angularjs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    build: ./nginx
    env_file:
      - ./env/.env
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 8000
        published: 8000
        mode: host
  angularjs:
    restart: always
    image: infrastructureplayground/angularjs:latest
    build: ./angularjs
    env_file:
      - ./env/.env
    ports:
      - 4200:4200
      - 49153:49153
    volumes:
      - ./angularjs:/usr/src/app/

