version: '3.6'
services:
  django:
    restart: always
    image: infrastructureplayground/django:latest
    build:
      context: ./django
      dockerfile: Dockerfile.start
    volumes:
      - ./django:/usr/src/app/
    env_file:
      - ./env/.postgres
  angularjs:
    restart: always
    image: infrastructureplayground/angularjs:latest
    build:
      context: ./angularjs
      dockerfile: Dockerfile.start
    volumes:
      - ./angularjs:/usr/src/app/
