apiVersion: v1
kind: Service
metadata:
  labels:
    run: django-api
  name: django-api
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: django-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}