apiVersion: v1
kind: Service
metadata:
  labels:
    run: django-proxy
  name: django-proxy
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    run: django-proxy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}